### ISSUE TITLE
[Fullstack] Intro Blurbs

### ISSUE THREAD

**Issue by jkairoy** [FullStackAtBrownTeam/project-first-at-brown#43]
- [x] Backend (schemas and updating tests and endpoints) @AdamWang00 
- [x] Frontend (update account page) @tanjoshua

**Comment by AdamWang00** [comment]
Instead of adding a "blurb" field to accounts, I think we can consider replacing our current "concentration" field with "blurb", since first-years usually include their interests in their blurb anyways and often don't know what they want to concentrate in.

This would also make this task a lot easier 🙃

**Comment by tanjoshua** [comment]
Hmm i think its fine to keep both separate but I don't feel very strongly about it
